spring:
  application:
    name: coupon-service

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/coupon_db}
    username: ${DB_USERNAME:coupon_user}
    password: ${DB_PASSWORD:coupon_pass}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      timeout: 2000

server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql: WARN

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

app:
  geo:
    ip:
      base-url: ${GEO_BASE_URL:https://ipapi.co}
      connect-timeout-ms: 2000
      read-timeout-ms: 2000
  cache:
    ip-country-ttl-seconds: 3600